Fix VMDBLogger NoMethodError "instrument"
The `$fog_log` has to respond to `#instrument`

```
13) ManageIQ::Providers::Openstack::InfraManager::Refresher will perform a full refresh
    Failure/Error: Fog.const_get(service).new(opts)

    Fog::Service::NotFound:
      openstack has no compute service

  --- Caused by: ---
  NoMethodError:
    undefined method `instrument' for #<VMDBLogger:0x00000000038f73e0>
    ./lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb:81:in `raw_connect'
```